### ISSUE TITLE
no overlap in reference-only mode

### ISSUE THREAD

**Issue by evo-eco-gen** [Xingyu-Liao/LongRepMarker_v2.0#8]
Hello,

I ran the reference-only mode following the basic instructions. The reference is a well-assembled genome (a mammal, PacBio HiFI, N50 of 23Mbp, total length 2.3gbp).

java -Xmx88g -Xms4g LongRepMarker -r /my_dir/my_reference.fasta -k 49 -m 100 -t 40 -o /my/output/dir

Unfortunately I get this. I have no idea what could be causing tis error. I thought that this mode is for scanning the sequence itself without extra inputs. Do some parameters (-m ?) need to be changed?

=======================================Detection===========================================
Step02: Parallel preprocessing [ Time Cost: 7365(ms) ] 
Step03: Loading reference sequences / assemblies [ Time Cost: 25458(ms) ] 
Step04: Finding overlap sequences between reference sequences / assemblies [ Time Cost: 
[ Error #04-1 ]: minimap2 cannot obtain the overlap sequences between assembled contigs. Please check the coverage and quality of the input data.

**Comment by evo-eco-gen** [comment]
Hi there! Any ideas, please? Am I just being incredibly stupid and missing something completely obvious?

**Comment by Xingyu-Liao** [comment]
> Hello,
> 
> I ran the reference-only mode following the basic instructions. The reference is a well-assembled genome (a mammal, PacBio HiFI, N50 of 23Mbp, total length 2.3gbp).
> 
> java -Xmx88g -Xms4g LongRepMarker -r /my_dir/my_reference.fasta -k 49 -m 100 -t 40 -o /my/output/dir
> 
> Unfortunately I get this. I have no idea what could be causing tis error. I thought that this mode is for scanning the sequence itself without extra inputs. Do some parameters (-m ?) need to be changed?
> 
> =======================================Detection=========================================== Step02: Parallel preprocessing [ Time Cost: 7365(ms) ] Step03: Loading reference sequences / assemblies [ Time Cost: 25458(ms) ] Step04: Finding overlap sequences between reference sequences / assemblies [ Time Cost: [ Error #4-1 ]: minimap2 cannot obtain the overlap sequences between assembled contigs. Please check the coverage and quality of the input data.

-----------------------------------------------------------------------------

Hi,

Sorry to reply to you late. 
I think the problem you're having may be caused by the minimap2 tool being unsuccessful installed, or it cannot use the assemblies you provided to generate the overlap sequences. 

This problem can be easily verified by the following command.

1)  >> cd ~/LongRepMarker_v2.1.2-master/
     >> minimap2

Please check whether the following information can display normally.

![image](https://user-images.githubusercontent.com/60574102/184872233-c6314536-e8b7-4b7b-a763-703413b925ef.png)

2) >> minimap2 -x ava-pb -g 3000 -w 10 -k 19 -m 100 -r 150 -t 8 /my_dir/my_reference.fasta /my_dir/my_reference.fasta > ~/LongRepMarker_v2.1-master/alignment/ovlp.paf

Please check whether the "ovlp.paf" file can be generated successfully.

![image](https://user-images.githubusercontent.com/60574102/184873259-5ac551b4-f096-4c96-bbe1-87c6527bb178.png)

![image](https://user-images.githubusercontent.com/60574102/184873352-95f4efec-8b2f-44a5-85c3-43b627a19de4.png)

![image](https://user-images.githubusercontent.com/60574102/184873414-50cebb9e-e8a1-415d-8132-37bb419386c3.png)


Thanks for your feedback. If the problem still cannot be resolved, please get in touch with me again.

Best,

Xingyu Liao

**Comment by evo-eco-gen** [comment]
Hi,

OK, it turns out that because of a problem with conda I did not have minimap2 installed correctly. Once I fixed it, it does work as you promise. Thank you!
